---
include:
  - board: nice_nano@2//zmk
    shield: settings_reset
  - board: xiao_ble//zmk
    shield: settings_reset

  # ---- Sofle ----
  - board: nice_nano@2//zmk
    shield: sofle_dongle dongle_display_091_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: sofle_dongle

  - board: nice_nano@2//zmk
    shield: sofle_left custom_nice_view_adapter custom_nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: sofle_central_left

  - board: nice_nano@2//zmk
    shield: sofle_left custom_nice_view_adapter custom_nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_peripheral_left

  - board: nice_nano@2//zmk
    shield: sofle_right custom_nice_view_adapter custom_nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_peripheral_right

  # ---- Corne ----
  - board: nice_nano@2//zmk
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: corne_central_left

  - board: nice_nano@2//zmk
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_peripheral_right

  # ---- Keyball ----
  - board: nice_nano@2//zmk
    shield: keyball61_left
    artifact-name: keyball_left

  - board: nice_nano@2//zmk
    shield: keyball61_right
    artifact-name: keyball_right

  # ---- roBa ----
  - board: xiao_ble//zmk
    shield: roBa_R
    artifact-name: roBa_right
    snippet: studio-rpc-usb-uart
  - board: xiao_ble//zmk
    shield: roBa_L
    artifact-name: roBa_left