---
include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: soflew_dongle dongle_display_091_oled
  - board: nice_nano_v2
    shield: soflew_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: soflew_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  # - board: nice_nano_v2
  #   shield: sofle_left nice_view_adapter nice_view
  # - board: nice_nano_v2
  #   shield: sofle_right nice_view_adapter nice_view
