---
include:
  - board: nice_nano_v2
    shield: settings_reset

  # ---- Sofle ----
  - board: nice_nano_v2
    shield: soflew_dongle dongle_display_091_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=6 -DCONFIG_BT_MAX_CONN=8 -DCONFIG_BT_MAX_PAIRED=8
    artifact-name: soflew_dongle

  - board: nice_nano_v2
    shield: soflew_left soflew_nice_view_adapter cat_nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: soflew_central_left

  - board: nice_nano_v2
    shield: soflew_left soflew_nice_view_adapter cat_nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: soflew_peripheral_left

  - board: nice_nano_v2
    shield: soflew_right soflew_nice_view_adapter cat_nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: soflew_peripheral_right

  # ---- Corne ----
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: corne_central_left

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_peripheral_right