# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&caps_word': Caps Word
    '&studio_unlock': Studio

    '&out OUT_TOG': Out Toggle
    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE
    '&ext_power EP_TOG': Pwr Toggle

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_CLR': BT Clear

    '&tog GAME': Toggle Game

    '&kp LC(LS(ESCAPE))': Task Mgr
    '&kp LS(LG(S))': Screenshot
    '&kp LA(LC(G))': Alt+Ctrl+G
    '&kp LC(Y)': Redo
    '&kp LC(Z)': Undo

    '&mkp MB1': Left Click
    '&mkp MB2': Right Click
    '&mkp MB3': Middle Click
    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click

    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →

    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →

  zmk_combos:
    combo_ctrlalttab: {align: bottom}

  zmk_keycode_map:
    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    LEFT_SHIFT: Shift
    RIGHT_SHIFT: Shift
    ESC: Esc
    ESCAPE: Esc
    SPACE: ␣
    BSPC: ⌫
    BACKSPACE: ⌫
    RET: ⏎
    ENTER: ⏎
    TAB: ↹
    DEL: ⌦

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    PG_UP: Page ↑
    PG_DN: Page ↓
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn

    C_MUTE: Mute
    C_VOL_UP: Vol ↑
    C_VOLUME_UP: Vol ↑
    C_VOL_DN: Vol ↓
    K_PLAY_PAUSE: ⏯
    C_PP: ⏯
    K_NEXT: ⏭
    C_NEXT: ⏭
    K_PREV: ⏮
    C_PREV: ⏮

    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: auto
