manifest:
  remotes:
    - name: garrettfaucher
      url-base: https://github.com/garrettfaucher
  projects:
    - name: zmk
      remote: garrettfaucher
      revision: main
      import: app/west.yml
  self:
