manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: garrettfaucher
      url-base: https://github.com/garrettfaucher
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display-091-oled
      remote: garrettfaucher
      revision: mulitple-peripheral-count
    - name: zmk-keyboards-soflew
      remote: garrettfaucher
      revision: main
    - name: zmk-nice-view-custom-art
      remote: garrettfaucher
      revision: main
  self:
    path: config
