manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: garrettfaucher
      url-base: https://github.com/garrettfaucher
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display-091-oled
      remote: garrettfaucher
      revision: main
    - name: zmk-driver-pmw3360
      remote: garrettfaucher
      revision: invert-x-y
  self:
    path: config
