manifest:
  remotes:
    - name: nguyendown
      url-base: https://github.com/nguyendown
    - name: garrettfaucher
      url-base: https://github.com/garrettfaucher
  projects:
    - name: zmk
      remote: nguyendown
      revision: behaviors/non-overlapping
      import: app/west.yml
    - name: zmk-dongle-display-091-oled
      remote: garrettfaucher
      revision: main
  self:
    path: config
