name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - config/west.yml
      - config/*.keymap
      - config/*.conf
      - config/includes/*.dtsi
      - config/keypos_def/*.h
      - boards/**
      - build.yaml
      - zephyr/module.yml
      - .github/workflows/build.yml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3 