name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/includes/*.dtsi'
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap-drawer/config.yaml"
      output_folder: "assets/keymap-drawer"
      install_branch: main
      json_path: keymap-drawer/layouts
      amend_commit: true
