name: Draw ZMK keymaps
on: [workflow_dispatch]

jobs:
  draw:
    permissions:
      contents: write
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: "config/*.keymap"        # path to the keymaps to parse
      output_folder: "assets"
      commit_message: "Update keymap images"
